### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by bintangthunder** [saurabheights/DiabeticRetinopathyDetection#3]
I dont know which one script that will run first.thank you

**Comment by saurabheights** [comment]
@bintangthunder - Did you check https://github.com/saurabheights/DiabeticRetinopathyDetection#setup-and-training-model ?

P.S. - It will better to run this on ubuntu. It is possible on Windows as well, but you will have to setup all dependencies yourself, however this should not be much trouble, just requires a little googling.

Finally, please make sure you don't ask an abstract question. Be specific, like where you got stuck.

**Comment by bintangthunder** [comment]
Sure. Thank you. I will run in Ubuntu.
