### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by mrzhangzizhen123** [saurabheights/DiabeticRetinopathyDetection#6]
I used the Resnet18 model ,but I don't how to used other model .please can you tell me how to use other models?such as Resnet34.Resnet50.The configuration file references this--https://github.com/saurabheights/DiabeticRetinopathyDetection/blob/master/src/transfer_learning_configuration.py

**Comment by omsh** [comment]
Change the parameter `net_size` in the configuration file you mentioned, please see [here](https://github.com/saurabheights/DiabeticRetinopathyDetection/blob/678129495dd771f608ea6f5d14fe519addefa434/src/transfer_learning_configuration.py#L83).

**Comment by mrzhangzizhen123** [comment]
@omsh Thanks for your help. Do you have the code to test?In addition, have you debugged the visualization folder in the file?Can I see the debug code?
